[features]
seeds = false
skip-lint = false
[programs.localnet]
myepicproject = "DrcEfafDtNHtQ8WKoNLtcuQQtmzYbpqiH5ozGBKjJR2V"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/wura/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"


